services:
  dev-db:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: bingr
    networks:
      - bingr

networks:
  bingr:
